### ISSUE TITLE
Is this a relevant documentation?

### ISSUE THREAD

**Issue by doodong** [Payop/payop-api-doc#1]
Is this the documentation for the current version of API? It seems to be related to the earlier API version and outdated compared to what was available at [https://payop.com/apidoc/](https://payop.com/apidoc/) previously:

1. Invoice creation endpoint specified here is [https://payop.com/v1/invoices/create](https://payop.com/v1/invoices/create)
The documentation that was available before the migration to the new enterprise technology specified the address [https://payop.com/api/v1.1/payments/payment](https://payop.com/api/v1.1/payments/payment) for this endpoint.
The "older" URL points to the API version `v1.1` while the "newer" one is `v1`, and the "older" address looks more reasonable.

2. The names of the checkout parameters in the "new" documentation are somewhat inconsistent. Compare: `resultUrl` and `failPath`. The corresponding names in the "older" version are `resultUrl` and `failUrl`.

3. The _request signing_ is not documented at all.

4. The documentation available at the moment refers to the `txid` transaction identifier as an optional while the "older" documentation stated that it will replace the `id` parameter which can not provide uniqueness and this will be removed in the future.

5. According to the "current" version, the _IPN request_ contains just the transaction number, and the rest of the information, e.g. the processing status, etc, should be requested through the API. This extra request does not make any sense, why not include the transaction status immediately in the IPN.

**Comment by devtretyak** [comment]
It's documentation for new api.  We'll update it today.

**Comment by doodong** [comment]
Does this documentation describe the new API **now**, in its **current** state?
Then your new API is much poorer than the older one.

**Comment by devtretyak** [comment]
In fact, it would be better if you write a request in a ticket.

The new Api is definitely not poorer. And we will update the documentation.

**Comment by doodong** [comment]
Your ticket system allows to contact Sales and Finance only.
However we **did** create a ticket before opening this issue, and predictably received a formal uninformative response.

**Comment by doodong** [comment]
As for the documentation, I see it has been expanded, however the feature description remains the same.
E.g., the IPN request example gives the following:
```javascript
{
    "invoice": {
        "id": "54b8f367-8c4c-4495-969d-bf4cb46bceb2",
        "txid": null
    }
}
```

And this is the description from the "older" documentation:

Parameter | Request Method | Description
------------|--------------------|--------------
txid|GET &#124; POST|Unique transaction identifier in the Payop system.<br>Merchant have to use this parameter to make relation between merchant order and Payop transaction
status|GET &#124; POST|Transaction status in the Payop system:<br>wait — pending transaction payment<br>success — transaction is paid<br>error — improper processing of transaction
publicKey|GET &#124; POST|Payment application ID for Payop merchant
type|GET &#124; POST|Payment interface type (button, app)
amount|GET &#124; POST|Payment amount. 4 decimal places
currency|GET &#124; POST|Payment currency
signature|GET &#124; POST|Digital signature
language|GET &#124; POST|Language of payment countries (en, ru)
date|GET &#124; POST|Transaction creation date
orderId|GET &#124; POST|Transaction ID in the merchant system
email|GET &#124; POST|Customer email
error|POST|json object
||error.message|Description of the error
||error.code</div>|Error technical code

**Comment by devtretyak** [comment]
There are 2 options for using API.

For newly created projects we use the new API, for old projects we use the old one.

For new projects, we get IPN in short form:

     "invoice": {
         "id": "88597261-2031-4cf0-a180-3c9dfb7993ff",
         "txid": 65954f1e-ceba-49ca-a20d-e8bc70b9da3f
     }

For old projects - in a more expanded old form.

For a new project, after receiving the IPN, you must poll the transaction to get all the data about its status.

**Comment by doodong** [comment]
Thank you for the explanation, now I've got it.

Please consider expanding the "short" IPN info.
At least, it should contain the transaction status so that we can see if we need to request further information (we handle successful payments only). Transaction currency and amount wold save us (and you) extra request too.

I must note that we worked with many payment systems, and never seen an approach like this; they all send the full payment information without need to make extra requests.

Actually, splitting the payment info does not save any resources. OK, you don't have to sign the data. Other than that, your server will always receive extra request of the transaction info for every IPN, so why not include it immediately? You cold save a little by including the status info so that the merchants can skip the IPNs for the unfinished or cancelled transactions.

**Comment by mrkapable007** [comment]
It takes so long to activate the project, and additional payment ways, its been 3weeks now still no activation, it would be helpful if you could have more support to this.

**Comment by madmis** [comment]
> It takes so long to activate the project, and additional payment ways, its been 3weeks now still no activation, it would be helpful if you could have more support to this.

Please create ticket in the merchant admin panel or contact support by email.
Here is bad place for such kind of problems.

**Comment by mrkapable007** [comment]
I can understand it is, sent lots of support and no good update. i will resend again.

**Comment by madmis** [comment]
> I can understand it is, sent lots of support and no good update. i will resend again.

Tell me your ID (you can see it in admi panel) and name of your project. 
I'll ping support.

**Comment by mrkapable007** [comment]
> 
> 
> > I can understand it is, sent lots of support and no good update. i will resend again.
> 
> Tell me your ID (you can see it in admi panel) and name of your project.
> I'll ping support.

ID is : 2628
project name is : vicsenshop new and New payop

**Comment by madmis** [comment]
> ID is : 2628
> project name is : vicsenshop new and New payop

Today you'll get response from support about your project.

**Comment by mrkapable007** [comment]
> 
> 
> > ID is : 2628
> > project name is : vicsenshop new and New payop
> 
> Today you'll get response from support about your project.

Thanks a lot madmis, I appreciate your effort.
