### ISSUE TITLE
Unclear documentation about Transaction States

### ISSUE THREAD

**Issue by Sirozha1337** [Payop/payop-api-doc#28]
In this doc state https://github.com/Payop/payop-api-doc/blob/master/Transaction/getTransaction.md#successful-response-example
There is an example of a response that has fields "status" and "state", there is a description of transaction statuses below, but there is no description of transaction states.  
Also, status = 1 means that it's a new payment, but in the "data" field we see that it resulted in an error, so status should be 3 or 5.

**Comment by madmis** [comment]
`{"data": {"state": 5}, "status": 1}`

Data in the `data` object - related to transaction. So transaction state - this is property `data.state`.
Property `status` from the **root** object - it's request status. And it's legacy. 

But you are right. It's not clear. I'll remove request status from example and change **Transaction statuses** to **Transaction states**

**Comment by Sirozha1337** [comment]
That was quick!
Yes, it's clear now, thank you very much!
