### ISSUE TITLE
Error: No route found for "Get/V1/checkout/page/invoice-processing/countrycode

### ISSUE THREAD

**Issue by Snwocatcher** [Payop/payop-api-doc#31]
Title basically, in this case the error code is:
 Error: 
No route found for "Get/V1/checkout/page/invoice-processing/RO"

Happens after leaving the final page for checkout/order now of the website where payop is implemented as payment method, and the first page it should take to for the redirect where people should select their payment methods (it doesnt display the latter where it should redirect to).

This is the url: https://payop.com/en/payment/invoice-preprocessing

This is how the page looks instead having the payment method options.
![payop error page](https://user-images.githubusercontent.com/63865022/79585868-b1a2a280-80d0-11ea-91d9-b048fccbd098.jpg)

**Comment by madmis** [comment]
Hi @Snwocatcher, we are on it. Thanks for let us know.

**Comment by Snwocatcher** [comment]
alright, lmk once this is fixed so we can reinstate it as default payment method.

**Comment by Payop** [comment]
@Snwocatcher my team tell's me that it's fixed.  Could you please check?
