### ISSUE TITLE
Lack of payout methods documentation

### ISSUE THREAD

**Issue by basherru** [Payop/payop-api-doc#35]
Hi, guys!

Can you, please, update the documentation with all possible payout payment methods?

You have a decent feature with getting currently available payment methods from API, but in order to handle them properly I need to know each method's identifier, type or title.

Although, I know a title for each of methods declared implicitly in the payout payment methods API reference, it would be much stronger solution if I could rely on type or identifier.

**Comment by basherru** [comment]
The same concerns about pay-in methods.

**Comment by Payop** [comment]
> Can you, please, update the documentation with all possible payout payment methods

@basherru we can't. Because list of payment method different for each client. 

For more info please contact Payop support.
