### ISSUE TITLE
Payop Update Step 1 Issue

### ISSUE THREAD

**Issue by aamiiryounus** [Payop/payop-api-doc#36]
i am using your services to take payments from my clients.

Recently we got an email about the update you guys told about namely 
step 1
https://github.com/Payop/payop-api-doc/blob/master/Checkout/checkout.md#ipn
step 2
https://github.com/Payop/payop-api-doc/blob/master/Checkout/checkTransactionStatus.md

I am trying to authenticate the IP that i get the request from at my ipn url. The ip I am getting requests from is 192.254.250.183

while it should be 
'52.49.204.201' OR '54.229.170.21' 

could you please confirm?

Thanks

**Comment by Trojaner** [comment]
This could be caused by reverse proxies

**Comment by aamiiryounus** [comment]
I would not be so sure about that! because Payop sent an email regarding this ip and explicitly mentioned, and the ipn request has to be checked if that is made by that specific IP, so our explicit php objects should have this IP ('52.49.204.201' OR '54.229.170.21') so that we can verify

**Comment by aamiiryounus** [comment]
The IP i am getting in my php explicit objects is from my own server basically! 

could you please advise how am i suppose to the get the IP?

**Comment by Payop** [comment]
@aamiiryounus you have to configure your webserver to proxy real request IP to your application. But i can't  tell you more. But i'm sure you can find this info yourself. There a lot of examples about this on stackoverflow ([one example](https://stackoverflow.com/questions/5349604/how-to-track-the-real-ip-address-behind-the-proxy)).

This IP '52.49.204.201' OR '54.229.170.21' - are correct. 

Please contact Payop support if you have more questions.
