### ISSUE TITLE
Template expressions for resultUrl and failPath not working

### ISSUE THREAD

**Issue by PhiWeber** [Payop/payop-api-doc#40]
Hello, the template doesn't seem to work for the resultUrl and failPath. The placeholders don't get replaced.

 # Template
    https://your.site/result-page/?invoiceId={{invoiceId}}&txid={{txid}}
    # Result SHOULD BE
    https://your.site/result-page/?invoiceId=b8bf37ab-fc69-44df-bfeb-b9a879ce20b7&txid=1eeda2f2-d3e1-4edd-853e-3d897bc629b2
   # Result HOW IT IS
  https://your.site/result-page/?invoiceId={{invoiceId}}&txid={{txid}}

**Comment by madmis** [comment]
Thanks @PhiTheG

I have created bug for this issue. Will let you know when it will be fixed.

**Comment by madmis** [comment]
@PhiTheG fix has been released.
