### ISSUE TITLE
Api is broken 

### ISSUE THREAD

**Issue by abubakar-iqbal** [Payop/payop-api-doc#59]
I'm facing an issue regarding API, Once I made a call I'm getting the following error.

`Fatal error: Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST https://payop.com/api/v1.1/payments/payment` resulted in a `500 Internal Server Error` response: {"message":"Something went wrong, try again or contact support."}`

Could you please have a look?

**Comment by DenysVolynets** [comment]
@abubakar-iqbal Hi! You're using the old api which we don't support anymore. Current api-doc is what you need. Here is the minimal checkout flow: https://github.com/Payop/payop-api-doc/blob/master/Integration/hostedPage.md#minimal-checkout-flow
